# Generated by Django 2.2.6 on 2019-11-24 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='visting_places',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
